### ISSUE TITLE
Handle Forbidden StatusCode in ExceptionHandlerHelper

### ISSUE THREAD

**Issue by emog** [MarcinOrlowski/laravel-api-response-builder#105]
**Describe the bug**

**To Reproduce**
1. Add abort(403) in some API route
2. Make request to that route.
3. 
4. 

**Expected behavior**
I expect to work like abort(401). 
```php
{
    "success": false,
    "code": 114,
    "locale": "en",
    "message": "Forbidden",
    "data": null
}
```
**Environemnt:**Desktop (please complete the following information):**
 - Name and version of OS MacOS Catalina
 - PHP version 7.3
 - Laravel version 6.4.0

**Additional context**
Now in this case it returns:
```php
{
    "success": false,
    "code": 112,
    "locale": "en",
    "message": "HTTP exception Symfony\\Component\\HttpKernel\\Exception\\HttpException",
    "data": null
}
```

**Comment by MarcinOrlowski** [comment]
Thanks for the report. Currently ResponseBuilder returns full exception's class name if and only if there's no exception message provided. Returning class name while not really useful for end user is still better than returning empty string. In case of abort the method signature is:

    public function abort($code, $message = '', array $headers = [])

and that's why gets returned as you saw. However I think I can improve this return original HTTP error description instead, which would be actually pretty nice improvement and quick fix and I will add that. Thanks

**Comment by emog** [comment]
It will be good if you check is debug mode enabled or not to show the actual class.  I’m not sure but the package should handle is it ok to show the actual message for the exception because there could be some sensitive information. I’m not sure but I think it’s a real case.

**Comment by MarcinOrlowski** [comment]
That's valid note. Can you please create bug report for this?

**Comment by MarcinOrlowski** [comment]
Please take a look a this branch: [better-http-ex-msg](https://github.com/MarcinOrlowski/laravel-api-response-builder/tree/better-http-ex-msg) - the configuration for `ExceptionHandlerHelper` changed a bit but now one can easily configure any HTTP error code as he like. Default config [is here](https://github.com/MarcinOrlowski/laravel-api-response-builder/blob/better-http-ex-msg/config/response_builder.php#L75) and you can override everything in your own config.

**Comment by MarcinOrlowski** [comment]
This code is now in v6.4-dev branch if you want to play with it. It will be in 6.4 release once shortly. Please play with it and give some feedback before it goes officially out.

**Comment by MarcinOrlowski** [comment]
Closing as fixed.
