### ISSUE TITLE
Fix the response status code for ValidationException in ExceptionHandlerHelper

### ISSUE THREAD

**Issue by emog** [MarcinOrlowski/laravel-api-response-builder#106]
Please align the ValidationException code with the default one for laravel which is 422 instead of just 400 like in your code.

**To Reproduce**
1. Add a route validation
2. Make request to this route with invalid/missing data
3. 
4. 

**Expected behavior**
Receiving an status code 422

**Environemnt:**Desktop (please complete the following information):**
 - Name and version of OS: macOS Catalina
 - PHP version 7.3
 - Laravel version 6.4.0

**Comment by MarcinOrlowski** [comment]
I am closing as duplicate of #105  as this is the same area.
