### ISSUE TITLE
v6.3.1 not available on packagist and composer

### ISSUE THREAD

**Issue by FaridAghili** [MarcinOrlowski/laravel-api-response-builder#113]
https://packagist.org/packages/marcin-orlowski/laravel-api-response-builder

Can't update to v6.3.1 with `composer update`

**Comment by MarcinOrlowski** [comment]
It seems that packagist did not pick up that version for yet unknown reason. I manually triggered its update and 6.3.1 should be available via composer. Thanks for the info.
