### ISSUE TITLE
Set custom header in response

### ISSUE THREAD

**Issue by FaridAghili** [MarcinOrlowski/laravel-api-response-builder#117]
Is there a way to send header with response?

For example:
```php
ResponseBuilder::error(ApiCodes::IP_ADDRESS_FLOOD, [
    'Retry-After' => 3600
]);
```

**Comment by MarcinOrlowski** [comment]
No, not in current release. This is already addressed in code heading for v6.4 as it comes with Builder that allows you to combine any element you want.

**Comment by MarcinOrlowski** [comment]
Closing as fixed. This is now available in `v6.4-dev` branch. Examples on how to use new `Builder` class: https://github.com/MarcinOrlowski/laravel-api-response-builder/blob/9683c61726586c5247741a319821cc375e240619/src/ResponseBuilder.php#L124

**Comment by FaridAghili** [comment]
Thank you, but non of the gives a way of setting custom header.
Take a look at:
https://laravel.com/docs/6.x/responses#attaching-headers-to-responses

**Comment by MarcinOrlowski** [comment]
You need to use Builder class for this, like in this test: https://github.com/MarcinOrlowski/laravel-api-response-builder/blob/v6.4-dev/tests/Builder/BuilderTest.php#L45
