### ISSUE TITLE
On the ExceptionHandler the render should check for if it's a Ajax request.

### ISSUE THREAD

**Issue by dragonfire1119** [MarcinOrlowski/laravel-api-response-builder#12]
When I just used ``return ExceptionHandlerHelper::render($request, $e);`` it even responded with a json response on regular http 404 error in the browser. Which would not be user friendly.

```
public function render($request, Exception $e)
{
        if ($request->ajax() || $request->wantsJson())
        {
            return ExceptionHandlerHelper::render($request, $e);
        }
        
        return parent::render($request, $e);
}
```

So I think it should check for if it's a ajax request. The user just needs to add the ``Accept:application/json`` header. Or if you have a better way that would be awesome to see!

**Comment by MarcinOrlowski** [comment]
This is intentional and by design API must always return standardized JSON response, no matter what happened. That is the purpose of that ErrorHandler - to ensure this works that way. There's no single benefit from breaking that rule.

**Comment by dragonfire1119** [comment]
@MarcinOrlowski so your saying I need to split my api up & not have a site & api on the same install?  It's still is not user friendly for a customer to see a 404 json response when they're browsing the site? They should see a 404 blade view response.

**Comment by MarcinOrlowski** [comment]
I am saying that your API should ** ALWAYS** return JSON. This is what clients (programs, not humans!) consuming your API expect. There's absolutely no reason to return HTML from API. HTML error code 404 is also no exception from that. My ExceptionHandler will return standarized JSON, with `success` being `false` and closer details in `message`. This is perfectly sufficient for automated handling.

And yes, separating API from main is a good thing. If both codes (API and website) share some code (i.e. models) you may create 3rd package with these elements and have them included in both projects via composer. Alternatively you need to modify the code to better handle 404, i.e. if request is for `api/foo/bar` and `bar` does not exists, then you need tor return JSON as this is api path, but if you face `pages/bar` and `bar` is non existing, then you need to return HTML 404. Lot of pointless work. Do the separation.
