### ISSUE TITLE
success() method undefined error

### ISSUE THREAD

**Issue by raakkan** [MarcinOrlowski/laravel-api-response-builder#126]
I'm trying to use the success() method in my controller but this returns an error.

**Comment by MarcinOrlowski** [comment]
You seem to miss the line

    use use MarcinOrlowski\ResponseBuilder\ResponseBuilder;

in your code. Then the invocation would be `ResponseBuilder::success();`.

**Comment by MarcinOrlowski** [comment]
Feel free to reopen if I'm wrong, but then you need to provide more info about your code that does not work.
