### ISSUE TITLE
Pagination with Laravel API Resource Collections

### ISSUE THREAD

**Issue by mbaxter91288** [MarcinOrlowski/laravel-api-response-builder#127]
Not sure this is 100% correct place, but I've seen people are really active so hoping this is ok?

This has been briefly mentioned in #109 but I must be missing something. Still not sure how to best get additional pagination information with the request. So far I have:

```
public function index(Request $request)
    {
        return ResponseBuilder::success(new GraphicDownloadCollection(GraphicDownload::byAccount($request->user()->account->id)->jsonPaginate()));
    }
```
**NOTE** The `jsonPaginate` comes from [https://github.com/spatie/laravel-json-api-paginate](https://github.com/spatie/laravel-json-api-paginate), but even if I put standard Laravel paginate, I get same result.

Which returns:
```
{
    code: 0
    data: {
        items: {
            current_page: 1
            data: []
            first_page_url: "http://domain.test/api/v1/graphic-downloads?page%5Bnumber%5D=1"
            from: null
            last_page: 1
            last_page_url: "http://domain.test/api/v1/graphic-downloads?page%5Bnumber%5D=1"
            next_page_url: null
            path: "http://domain.test/api/v1/graphic-downloads"
            per_page: 10
            prev_page_url: null
            to: null
            total: 0
            locale: "en"
            message: "OK"
            success: true
        }
    }
}
```
Seems a better response would be:
```
{
    code: 0
    data: {
        current_page: 1
        items: []
        first_page_url: "http://domain.test/api/v1/graphic-downloads?page%5Bnumber%5D=1"
        from: null
        last_page: 1
        last_page_url: "http://domain.test/api/v1/graphic-downloads?page%5Bnumber%5D=1"
        next_page_url: null
        path: "http://domain.test/api/v1/graphic-downloads"
        per_page: 10
        prev_page_url: null
        to: null
        total: 0
        locale: "en"
        message: "OK"
        success: true
    }
}
```
This is my `ResourceCollection` class for that particular model:
```
<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\ResourceCollection;

class GraphicDownloadCollection extends ResourceCollection
{
    /**
     * Transform the resource collection into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request = null)
    {
        return $this->resource;
    }
}
```

Any help would be greatly appreciated.

**Comment by MarcinOrlowski** [comment]
I am almost sure that it should be now safe to have this behavior either changed or made configurable in v6.4. For now you need to do something like this:

    ResponseBuilder::success($your_object->toArray());

but I do agree that's ugly.

**Comment by mbaxter91288** [comment]
Not sure if an easy solution would be to:
```
Illuminate\Http\Resources\Json\ResourceCollection::class => [
	"key" => "",
	"method" => "toArray",
	"pri" => 10,
],
```
If the `key` is empty or `false` or something, merge into the data. That would give me the 2nd example output above?

**Comment by MarcinOrlowski** [comment]
Please check recent v6.4-dev branch. It supports "key" being optional (in your case you need to comment "key" entry out). Let me know if you spot any issue.

**Comment by mbaxter91288** [comment]
Awesome, thanks. I've been re-assigned to another project for last few days, should be back on it tomorrow or Friday so I'll check then and let you know.

Appreciate your work

**Comment by mrelevance** [comment]
@MarcinOrlowski 
I just tried using a Resource Collection with v6.4-dev and am getting an exception when the builder tries the convert the `ResourceCollection` class using the `toArray()` method as it is expecting a request object to be passed in.

https: //laravel.com/api/6.x/Illuminate/Http/Resources/Json/ResourceCollection.html#method_toArray

After some poking around and experimenting, I think I've found a solution that should work. I will preface this by saying that I am using v6.4-dev with Laravel 5.5 as it does seem to work with only one modification, I only needed to change the class name of the JsonResource class in the config to match Laravel 5.5's namespace/class name.

I've gotten pagination to work with Resource Collection by doing the follow:

Create a new converter class to handle `ResourceCollection` classes
```php
class MyJsonResourceCollectionConverter implements ConverterContract
{
    public function convert($obj, array $config): array
    {
        return $obj->response()->getData(true);
    }
}
```

Build the API response with your `JsonResource` or `JsonResourceCollection` class.
```php
SpecResource::wrap('items');

return Builder::success()
                ->withData(SpecResource: :collection($specs))
                ->build();
```
This will then produce the following output:
```json
{
    "success": true,
    "code": 0,
    "locale": "en",
    "message": "OK",
    "data": {
        "items": [
            {
                "id": 137,
                "uuid": "b2f94a2f-42a8-4b9b-8e56-ea3ef54987f2",
            }
        ],
        "links": {
            "first": "https://example.com/api/public/v1/specs?page%5Bnumber%5D=1",
            "last": "https://example.com/api/public/v1/specs?page%5Bnumber%5D=11",
            "prev": null,
            "next": "https://example.com/api/public/v1/specs?page%5Bnumber%5D=2"
        },
        "meta": {
            "current_page": 1,
            "from": 1,
            "last_page": 11,
            "path": "https://example.com/api/public/v1/specs",
            "per_page": 30,
            "to": 30,
            "total": 316
        }
    }
}
```
Here are the changes I made in order to get this to work: https://github.com/mrelevance/laravel-api-response-builder/commit/21510b393b01df705c78698c8fee2d737c77db13

I can make a pull request if you feel these changes are of good enough quality and make sure this will work with Laravel 6.

**Comment by MarcinOrlowski** [comment]
What Laravel version are you using? As workaround, please clone `ToArrayConverter.php` (located in https://github.com/MarcinOrlowski/laravel-api-response-builder/tree/v6.4-dev/src/Converters) and make its 23rd line look like this:

    return $obj->toArray(null);

**Comment by mrelevance** [comment]
I'm currently using Laravel v5.5.48.

Tested below using fresh install of Laravel 6.

I tried using the code you provided above, but noticed that I am unable to override the config file to supply my own custom handler as it seems like it isn't picking up the config after I published the vendor files (`php artisan **vendor:publish`).

If I do this, it works and doesn't throw an exception. However, it doesn't respect any pagination and it doesn't respect the `Resource::wrap('items')` method.
```php
return $obj->toArray(null);
```

**Comment by MarcinOrlowski** [comment]
Please note Laravel older than v6.0 is not supported. It does not mean RB would not work with it as it worked many years prior release of ResponseBuilder 6, but I no loner guarantee that. There're no tests against Laravel 5.x etc. 

As for `supply my own custom handler` - config override should work out of the box unless there's a bug. Will check.

**Comment by mrelevance** [comment]
It looks like this key is causing the issues with the config.
https://github.com/MarcinOrlowski/laravel-api-response-builder/blob/v6.4-dev/src/ResponseBuilder.php#L58

the published config file is `response_builder.php` when the key is `response-builder`

**Comment by MarcinOrlowski** [comment]
Good spot. The key indeed changed and the change was not documented. In fact it was just cosmetic change for me but it seems that I failed to foresee the impact on people upgrading and while I could add this to [compatibility](https://github.com/MarcinOrlowski/laravel-api-response-builder/blob/v6.4-dev/docs/compatibility.md) docs, I am now not sure this really matters what key is used as long as it's clear what we use. I [reverted this change](https://github.com/MarcinOrlowski/laravel-api-response-builder/commit/ee9bb84aac67ac1fb250373e034e5423925a926e) so it's back to `response_builder`.

And config override definitely work ([unittest](https://github.com/MarcinOrlowski/laravel-api-response-builder/blob/v6.4-dev/tests/tests/Converter/ConverterTest.php#L367)).

**Comment by MarcinOrlowski** [comment]
I am closing this as fixed. Please reopen or fill another ticket if you face any issues.
