### ISSUE TITLE
seems not compatible with L7

### ISSUE THREAD

**Issue by robov** [MarcinOrlowski/laravel-api-response-builder#138]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for marcin-orlowski/laravel-api-response-builder ^7.0 -> satisfiable by marcin-orlowski/laravel-api-response-builder[7.0.0, 7.0.1, 7.0.3].
    - Can only install one of: laravel/framework[v7.0.3, 6.x-dev].
    - Can only install one of: laravel/framework[6.x-dev, v7.0.3].
    - Can only install one of: laravel/framework[6.x-dev, v7.0.3].
    - Conclusion: install laravel/framework 6.x-dev
    - Installation request for laravel/framework (locked at v7.0.3, required as ^7.0) -> satisfiable by laravel/framework[v7.0.3].

**Comment by MarcinOrlowski** [comment]
Please post your `composer.json`

**Comment by MarcinOrlowski** [comment]
I just released v7.1.0 that address this issue. Thanks for pointing this out!
