### ISSUE TITLE
ResponseBuilder::success() doesn't work with paginate()

### ISSUE THREAD

**Issue by hmrneves1** [MarcinOrlowski/laravel-api-response-builder#143]
**Describe the bug**
Hi, after testing the package I saw that if we retrieve all data from a model with pagination and relations, the ResponseBuilder breaks because json_decode() expects parameter 1 to be string, array given.

**To Reproduce**
1. Retrieve model data like --- $posts = Posts::with('author')->paginate(5);
2. return ResponseBuilder::success($posts, 200);

**Expected behavior**

**Environemnt:**Desktop (please complete the following information):**
 - Name and version of OS: Win10
 - PHP version 7.4
 - Laravel version 7.16

Thanks.

**Comment by MarcinOrlowski** [comment]
Can you please post whole error message you are facing?

**Comment by MarcinOrlowski** [comment]
I just added explicit test for that case https://github.com/MarcinOrlowski/laravel-api-response-builder/blob/dev/tests/tests/ResponseBuilder/SuccessTest.php#L45 and it passes for me. Please ensure you are using recent version of the library and if you do and this still occurs please reopen and provide more details on how to reproduce this issue.
