### ISSUE TITLE
Response builder is not working with Laravel resource and resource collection

### ISSUE THREAD

**Issue by sachinkumar121** [MarcinOrlowski/laravel-api-response-builder#190]
**What's wrong?**
Resource Builder is not working with the resource collection objects. In my case, it is Resources\UserCollection Object

**Steps to reproduce the behavior:**
 1. Create [resource](https://laravel.com/docs/7.x/eloquent-resources#generating-resources) and [resource collection](https://laravel.com/docs/7.x/eloquent-resources#resource-collections)
 2. use the Resource Builder and resource collection in the controller.

```
use App\Http\Resources\User as UserResource;
use App\Http\Resources\UserCollection;
use MarcinOrlowski\ResponseBuilder\ResponseBuilder;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
    	$users = User::all();
        $collection = new UserCollection($users);
        return ResponseBuilder::success($collection);
    }
}
```
 3. Another version by using the collection method.

```
use App\Http\Resources\User as UserResource;
use App\Http\Resources\UserCollection;
use MarcinOrlowski\ResponseBuilder\ResponseBuilder;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
    	$users = User::all();
        $collection = NcfResource::collection($users);
        return ResponseBuilder::success($collection);
    }
}
```
**You will get this error when you run the step 2 code:-** Too few arguments to function App\\Http\\Resources\\UserCollection::toArray(), 0 passed in vendor\\marcin-orlowski\\laravel-api-response-builder\\src\\Converters\\ToArrayConverter.php on line 39 and exactly 1 expected

**You will get this error when you run the step 3 code:-** Too few arguments to function Illuminate\\Http\\Resources\\Json\\ResourceCollection::toArray(), 0 passed in vendor\\marcin-orlowski\\laravel-api-response-builder\\src\\Converters\\ToArrayConverter.php on line 39 and exactly 1 expected

**Expected behavior**
It should be working with the resource collection and Json\\ResourceCollection.

**Runtime environment**
 - Name and version of OS: Windows 10
 - PHP version: PHP 7.3.7
 - Laravel version: 7.30.4
 - ResponseBuilder version used: 9.2

**Notes**
Any additional information that may be helpful in diagnosing the problem.

**Comment by sachinkumar121** [comment]
Hi @ MarcinOrlowski any luck with this?

**Comment by MarcinOrlowski** [comment]
The quick fix for you is to edit `ToArrayConverter.php` in `src/converters` and replace

```php
return $obj->toArray();
```

in line 38 (current release) with

```php
return $obj->toArray(null);
```

Alternatively (which seems safer approach) you just copy this converter to your project and reconfigure ResponseBuilder to use your converter in place of original `ToArrayConverter`. You will remove that later once this bug is addressed.

I am still investigating what should be the right fix for this on my side (but perhaps it should as I still support L7). Will keep you posted.

**Comment by joelmellon** [comment]
I'm facing the same (or at least a very similar) issue. I expected Response Builder to support Illuminate\Http\Resources\Json\ResourceCollections but it doesn't in my case. I'm sure this is a little redundant for most people, but I really like the simplicity of Laravel's built-in JsonResponse, especially the ResourceCollection's super simple recursion functionality.

I get: `MarcinOrlowski\\ResponseBuilder\\Converters\\ToArrayConverter::convert(): Return value must be of type array, Illuminate\\Http\\Resources\\Json\\AnonymousResourceCollection returned`

ResourceCollections seems to build AnonymousResourceCollections, FYI. Also, it seems like calling toArray() on Resource(Collection)s, doesn't necessarily return an array, so in no way does your code seem to be at fault. See [here](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Http/Resources/Json/ResourceCollection.php#L98).

I'm honestly not sure what the solution is here, but I'd really like to use my existing Resources to wrap with ResponseBuilder.

**Comment by MarcinOrlowski** [comment]
Can you please open new ticket (it's fine you copy paste your former post). Feel free to link to this particular ticket if needed too.

**Comment by NathanGwilliam** [comment]
We are also thankful to you for creating this package and provide support quickly. Keep it up. @MarcinOrlowski

**Comment by sachinkumar121** [comment]
We are also thankful to you for creating this package and provide support quickly. Keep it up. @MarcinOrlowski
