### ISSUE TITLE
DefaultExceptionHandler should accept \Throwable as a second argument

### ISSUE THREAD

**Issue by genesiscz** [MarcinOrlowski/laravel-api-response-builder#194]
**What's wrong?**
Please put a clear and concise description of what the bug is.

I am sometimes getting
TypeError : MarcinOrlowski\ResponseBuilder\ExceptionHandlers\DefaultExceptionHandler::handle(): Argument #2 ($ex) must be of type Exception, TypeError given, called ...

It would make a sense to take Throwables too since it is a default handler..

**Comment by MarcinOrlowski** [comment]
Thanks for the report. It's now fixed in v9.2.3 that shall be out as soon as tests are completed.
