### ISSUE TITLE
Exceptionhandler cannot use custom MyResponseBuilder

### ISSUE THREAD

**Issue by liweijie0812** [MarcinOrlowski/laravel-api-response-builder#198]
**What's wrong?**
ExceptionHandler now expects `MyResponseBuilder ` instead of `ResponseBuilder`.

**Comment by MarcinOrlowski** [comment]
Can you please be more descriptive?

**Comment by MarcinOrlowski** [comment]
I am closing for now. Please reopen once you post more information that would justify this report as bug report. If this is just support question, please use [Discussions](https://github.com/MarcinOrlowski/laravel-api-response-builder/discussions) instead.
