### ISSUE TITLE
How to use with resource collection

### ISSUE THREAD

**Issue by vanthao03596** [MarcinOrlowski/laravel-api-response-builder#199]
In config file, i can't find class handler ResourceCollection paginate. Can some one help me to use with 
ResourceCollection paginate

**Comment by MarcinOrlowski** [comment]
I am closing this as it does not look like a bug report for me (please reopen if you disaggree). But all support questions should rather be posted via [Discussions](https://github.com/MarcinOrlowski/laravel-api-response-builder/discussions) instead. Thanks.

**Comment by vanthao03596** [comment]
@MarcinOrlowski i created Discussions in #200
