### ISSUE TITLE
Custom key for Exceptions

### ISSUE THREAD

**Issue by pajkho** [MarcinOrlowski/laravel-api-response-builder#229]
Would be great if you could also customize the key for the exceptions. For example we would want this:

```json
{
    "success": false,
    "code": 115,
    "locale": "sv",
    "message": "The given data was invalid.",
    "data": {
        "messages": {
            "page": [
                "The page field is required."
            ]
        }
    },
}
```

to become like this below. But cant find any way to achieve this. Is this possible?

```json
{
    "success": false,
    "code": 115,
    "locale": "sv",
    "message": "The given data was invalid.",
    "errors": {
        "messages": {
            "page": [
                "The page field is required."
            ]
        }
    },
}
```

**Comment by MarcinOrlowski** [comment]
The only way to do that is to extend `ResponseBuilder` as documented in ["Manipulating response object"](https://github.com/MarcinOrlowski/laravel-api-response-builder/blob/master/docs/response.md) chapter.
