### ISSUE TITLE
Undefined array key "handler"

### ISSUE THREAD

**Issue by devaygun** [MarcinOrlowski/laravel-api-response-builder#230]
# What is wrong? #

Occassionally the exceptions are not fully rendered as the `$handler = new $cfg[ RB::KEY_HANDLER ]();` fails to work, as the array key "handler" is undefined?

This might be loosely linked to this existing issue: https://github.com/MarcinOrlowski/laravel-api-response-builder/issues/226

## Steps to reproduce the behavior: ##

1. Follow the exception handler helper [setup instructions](https://github.com/MarcinOrlowski/laravel-api-response-builder/blob/master/docs/exceptions.md#using-exception-handler-helper)
2. Occassionally for an unknown reason you will start to see receive: `Undefined arrray key "handler"`

## Expected behavior ##

The exception should render.

## Environment ##

* Name and version of OS: Happens locally (macOS) and other environments (Ubuntu) 
* PHP version: 8.1
* Laravel version: 9
* ResponseBuilder version used: v9.1

## Notes ##

Any additional information that may be helpful diagnosing the problem.

**Comment by MarcinOrlowski** [comment]
@denizaygun Can you please come with any steps to reproduce? "Occasionally" is pretty counter-precise and barely useful for any debugging.

**Comment by MarcinOrlowski** [comment]
Closing as dead
