### ISSUE TITLE
Update to Laravel 10?

### ISSUE THREAD

**Issue by dragonfire1119** [MarcinOrlowski/laravel-api-response-builder#237]
# What is wrong? #

This package is still requiring ^9.0

```
[laravel/framework](https://packagist.org/packages/laravel/framework): ^9.0
```

Are there any blocking issues?

**Comment by MarcinOrlowski** [comment]
That's intentional but there will be separate release for v10. I will try to push it today

**Comment by dragonfire1119** [comment]
> That's intentional but there will be separate release for v10. I will try to push it today

Thanks for the fast reply and your help! I appreciate it!

**Comment by MarcinOrlowski** [comment]
v10 released.
