### ISSUE TITLE
Uncaught RuntimeException: Missing "{$keyName}" for "{$className}"

### ISSUE THREAD

**Issue by dragonfire1119** [MarcinOrlowski/laravel-api-response-builder#31]
I'm getting this error ``Uncaught RuntimeException: Missing "{$keyName}" for "{$className}"`` ever since I updated with composer.

My composer version: ^2.1
Tried 3.0.1

**Comment by MarcinOrlowski** [comment]
Not sure why you closed this - it's a bug in the `getClassesMapping()`.

Quick solution is to check you config as "classes" mapping lacks either `key`  or `method`  entry for class.

**Comment by MarcinOrlowski** [comment]
Fixed in 3.0.2

**Comment by dragonfire1119** [comment]
@MarcinOrlowski I closed it because I looked at the github config & copied the 
```
Illuminate\Database\Eloquent\Model::class => [
		'key'    => 'item',
		'method' => 'toArray',
	],
	Illuminate\Database\Eloquent\Collection::class => [
		'key'    => 'items',
		'method' => 'toArray',
	],
```

It started working again on the 3.0 so I didn't want to waste your time.

**Comment by MarcinOrlowski** [comment]
My point is that if your report the issue then even you worked it around on your side, you should let the ticket opened for me to investigate. And even if you'd find that it was your fault then you should rather state this in comment and let the maintainer do the rest. Anyway, this time it was my bug, so thanks for the report :)
