### ISSUE TITLE
Getting this error after composer update

### ISSUE THREAD

**Issue by harishsn** [MarcinOrlowski/laravel-api-response-builder#47]
RuntimeException: Missing "{$keyName}" for "{$className}" mapping in /var/www/healthbeeps/vendor/marcin-orlowski/laravel-api-response-builder/src/ResponseBuilder.php:58

**Comment by MarcinOrlowski** [comment]
What version you got installed and what is the version you are updating to? 

In general as quick fix you need to check config file and add what is missing. 

https://github.com/MarcinOrlowski/laravel-api-response-builder/blob/master/config/response_builder.php

**Comment by MarcinOrlowski** [comment]
To me you it looks you need to check your `composer.json` as you are not updating to recent version. Check that to ensure you have either `3.2.0` or `^3.2.0`.

I am closing as invalid. Reopen if needed.

**Comment by harishsn** [comment]
It was a issue with config file after updating to latest version. That quick fix config file helped me. Thanks

**Comment by MarcinOrlowski** [comment]
I know, but the trick is that error message you quoted is from recent version, so aside from config, check you really updated
