### ISSUE TITLE
Laravel Form Requests not supported!

### ISSUE THREAD

**Issue by dragonfire1119** [MarcinOrlowski/laravel-api-response-builder#48]
When I use the FormRequest it just gives me a 500 internal error instead of giving me a array of the fields that failed validation.

**Comment by MarcinOrlowski** [comment]
First, you need to check your server's `error.log`.

**Comment by dragonfire1119** [comment]
@MarcinOrlowski Ok you didn't understand the laravel api response works just it doesn't work/use the FormRequest. It's throwing a ``Illuminate\\Validation\\ValidationException`` but api response is not handling it right.

The message just says this ``"message": "The given data failed to pass validation.",`` that doesn't tell you what fields failed the validation?

Right now I'm using it the bloated way.

```
        $validator = Validator::make($request->all(), [
		'name' => 'required|max:191',
        ]);

	if ($validator->fails()) {
            return ResponseBuilder::errorWithMessageAndData(ErrorCode::VALIDATION_ERROR, 'Validation errors', [
                'message' => $validator->messages()->first(),
                'messages' => $validator->messages(),
            ]);
        }

```

Which is allot of code that the FormRequest can resolve.

**Comment by dragonfire1119** [comment]
Ok this is another situation where your custom exception handler doesn't check if it's a instanceof ValidationException.

https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/Exceptions/Handler.php#L115

**Comment by MarcinOrlowski** [comment]
What version of Laravel you use?

**Comment by dragonfire1119** [comment]
@MarcinOrlowski This current project is using 5.4

**Comment by dragonfire1119** [comment]
I made a temporary fix until you investigate a fix.

```
if ($request->expectsJson())
{
    if($e instanceof ValidationException) {
        $errors = $e->validator->errors();
        return ResponseBuilder::errorWithMessageAndData(ErrorCode::VALIDATION_ERROR, 'Validation errors', [
            'message' => $errors->first(),
            'messages' => $errors->getMessages(),
        ]);
    } else if($e instanceof AuthorizationException) {
        return ResponseBuilder::errorWithHttpCode(ErrorCode::UNAUTHORIZED, ErrorCode::UNAUTHORIZED);
    }
    return ExceptionHandlerHelper::render($request, $e);
}
```

**Comment by MarcinOrlowski** [comment]
It seems I need to update Exception Handler helper code as it is not fully compatible with recent Laravel. AFAIR it sticks to 5.2 flow, yet there are changes in recent Laravel that remain uncovered. IT will be addressed in next release. 

Thanks for the feedback. Keep it coming.

**Comment by MarcinOrlowski** [comment]
Any reason you did `'messages' => $errors->getMessages(),` instead of `'messages' => $errors->all(),`?

**Comment by MarcinOrlowski** [comment]
Added in @dev
