### ISSUE TITLE
Wrong config path when publishing using vendor:publish

### ISSUE THREAD

**Issue by dragonfire1119** [MarcinOrlowski/laravel-api-response-builder#49]
When I install the package on a brand new fresh install of Laravel 5.4 & call `vendor:publish` it creates a directory for the config file.

```
// Wrong
/config/response_builder.php/response_builder.php

// Right
/config/response_builder.php
```

The package config doesn't work when its in another directory under the config directory.

**Comment by MarcinOrlowski** [comment]
Thanks for reporting. Fixed in v3.2.1
