### ISSUE TITLE
Validation error message?

### ISSUE THREAD

**Issue by dragonfire1119** [MarcinOrlowski/laravel-api-response-builder#9]
I noticed when reading through the Readme you don't have anything for validation errors set in place?

Is this something you are planning on adding or have you already thought about it?

Thanks for your work & time on this project.

**Comment by MarcinOrlowski** [comment]
There're internal checks whenever necessary, so you need to elaboraborate more what you're missing.

**Comment by dragonfire1119** [comment]
Never mind I figured it out. Thanks for the quick response.
