### ISSUE TITLE
error when installing the package 

### ISSUE THREAD

**Issue by yassir3wad** [MarcinOrlowski/laravel-api-response-builder#91]
@php artisan package:discover --ansi
In ResponseBuilderServiceProvider.php line 89:
Class 'MarcinOrlowski\ResponseBuilder\Arr' not found

Laravel Version: 6.1

**Comment by MarcinOrlowski** [comment]
Thanks for the report. It will be fixed in 6.0.1 but for quick local fix you can edit that file (in your `vendor/` folder) and add missing `use`:

    use Illuminate\Support\Arr;

or replace line 89 to use `array_key_exists()`:

    if (array_key_exists($key, $merging)) {

**Comment by MarcinOrlowski** [comment]
Fixed.

**Comment by yassir3wad** [comment]
thanks @MarcinOrlowski
